### ISSUE TITLE
serde support

### ISSUE THREAD

**Issue by zkat** [kdl-org/kdl-rs#17]
There should be built-in support for Serialize/Deserialize in this crate.

**Comment by berwyn** [comment]
Hi Kat!

I've never before implemented serde support for a language, but I'd love to take a stab at that here! Would that be amenable to you?

**Comment by berwyn** [comment]
Ah, sounds good! I'll keep an eye out for that!

**Comment by Lucretiel** [comment]
WIP `serde` implementation is here: https://github.com/lucretiel/kaydle. It's coming along, slowly but surely. It's challenging because serde is very much a structured object / array format, whereas KDL is node-oriented, so I have an opinionated mapping from one to the other. Contributions are welcome, thought there's a lot about my design intent that I haven't written up in the comments yet, so until it hits 1.0 I may be pretty conservative in what I accept. I work on it every Sunday at 7pm EST on [twitch](twitch.tv/Lucretiel) and I'd be happy to talk at a high level about my design for anyone attending.

**Comment by gak** [comment]
@Lucretiel FYI your twitch link is broken.

**Comment by Lucretiel** [comment]
Fixed, thank you

**Comment by zkat** [comment]
This is now out of scope for kdl-rs. It's going to be a document-oriented parser.

**Comment by pipelight** [comment]
So what should we use for serde support?

**Comment by pipelight** [comment]
Thank you! This crate was nowhere to be found!!
